.SH NAME

malbolge \- estoric public-domain programming language

.SH SYNOPSIS

malbolge <file name>

.SH DESCRIPTION

Malbolge is a public-domain, estoric, VLL (very-low-level) programming language. It's impossible to learn
Malbolge, even if you have knowledge with high-level languages (e.g. C, Python, Java) or assembly languages.
Originally developed by Ben Olmstead, it is now part of the free-software cli-extras and relicensed under the GNU
General Public License, version 3 or later, to prevent nonfree copies, but the PD license remains for malbolge
in cli-extras.

Around < 1\% of people know Malbolge, compared to Python (approx 98.3\%), Java (approx 77.8\%) and C
(approx 57.9\%).

.SH REPORTING BUGS

Malbolge is part of cli-extras. Report bugs at: https://github.com/Tyler887/cli-extras/issues

.SH COPYRIGHT

Malbolge is either in the public domain or (at your option) under the GNU General Public License v3+.
